#!/usr/bin/env sh

# Description: run clang-format in place on hovered/selected files
#
# Shell: POSIX compliant
# Authors: Michal Ciesielski

file_path=$2/$1

. "$(dirname "$0")"/.nnn-plugin-helper

if [ -s "$selection" ]; then
    arr=$(tr '\0' '\n' < "$selection")
    clang-format-11 -style=file -i $arr

    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
else
    clang-format-11 -style=file -i $file_path
fi
